const mongoose = require('mongoose');

const liveWalletSchema = new mongoose.Schema(
  {
    walletKey: { type: String, default: 'default', unique: true, index: true },
    startingBalance: { type: Number, required: true, default: 0 },
    balance: { type: Number, required: true, default: 0 },
    realizedPnl: { type: Number, default: 0 },
    totalTrades: { type: Number, default: 0 },
    wins: { type: Number, default: 0 },
    losses: { type: Number, default: 0 },
    lastResetAt: { type: Date, default: null },
    strategy3EngineSettings: {
      symbol: { type: String, default: 'NIFTY' },
      lotCount: { type: Number, default: 1 },
      perTradeCost: { type: Number, default: 100 },
      ivLookbackDays: { type: Number, default: 20 },
      ivSpikeMultiplier: { type: Number, default: 1.15 },
      maxSpikeMultiplier: { type: Number, default: 2.5 },
      minOrHistoryDays: { type: Number, default: 3 },
      entryToTime: { type: String, default: '12:00' },
      spikeMode: { type: String, default: 'either' },
      orPercentileMin: { type: Number, default: 65 },
      targetVolCrushPct: { type: Number, default: null },
      stopVolExpandPct: { type: Number, default: null },
      ivExpandStopMult: { type: Number, default: 1.5 },
    },
    strategy4EngineSettings: {
      symbol: { type: String, default: 'NIFTY' },
      lotCount: { type: Number, default: 1 },
      entryTime: { type: String, default: '15:20' },
      entryWindowMinutes: { type: Number, default: 2 },
      dayCloseTime: { type: String, default: '15:15' },
      skipExpiryDay: { type: Boolean, default: true },
      perTradeCost: { type: Number, default: 100 },
    },
    strategy6EngineSettings: {
      symbol: { type: String, default: 'NIFTY' },
      lotCount: { type: Number, default: 1 },
      entryTime: { type: String, default: '09:20' },
      entryWindowMinutes: { type: Number, default: 2 },
      dayCloseTime: { type: String, default: '15:15' },
      skipExpiryDay: { type: Boolean, default: true },
      perTradeCost: { type: Number, default: 100 },
    },
    strategy7EngineSettings: {
      symbol: { type: String, default: 'NIFTY' },
      lotCount: { type: Number, default: 10 },
      entryTime: { type: String, default: '11:15' },
      entryWindowMinutes: { type: Number, default: 0 },
      stopLossPoints: { type: Number, default: 15 },
      targetProfitPoints: { type: Number, default: 0 },
      strikeMode: { type: String, default: 'ATM' },
      perTradeCost: { type: Number, default: 100 },
      minDirectionScore: { type: Number, default: 2 },
      enabledPeSignals: { type: [String], default: undefined },
      enabledCeSignals: { type: [String], default: undefined },
    },
    strategy7SkippedDateKey: { type: String, default: null },
    strategy7LastSkipReason: { type: String, default: null },
    strategy9EngineSettings: {
      symbol: { type: String, default: 'NIFTY' },
      lotCount: { type: Number, default: 5 },
      entryFromTime: { type: String, default: '09:20' },
      entryToTime: { type: String, default: '15:15' },
      eodExitTime: { type: String, default: '15:20' },
      stopLossPoints: { type: Number, default: 15 },
      trailingActivationPoints: { type: Number, default: 2 },
      trailingStepPoints: { type: Number, default: 2 },
      dojiBodyMaxPct: { type: Number, default: 0.2 },
      strikeMode: { type: String, default: 'ATM' },
      perTradeCost: { type: Number, default: 100 },
    },
    strategy11EngineSettings: {
      symbol: { type: String, default: 'NIFTY' },
      lotCount: { type: Number, default: 5 },
      entryFromTime: { type: String, default: '09:20' },
      entryToTime: { type: String, default: '15:15' },
      eodExitTime: { type: String, default: '15:20' },
      stopLossPoints: { type: Number, default: 8 },
      trailingActivationPoints: { type: Number, default: 4 },
      trailingStepPoints: { type: Number, default: 2 },
      strikeMode: { type: String, default: 'ATM' },
      perTradeCost: { type: Number, default: 100 },
    },
    strategy3OrHistory: {
      type: [{ dateKey: String, orIv: Number }],
      default: [],
    },
  },
  { timestamps: true }
);

module.exports = mongoose.models.LiveWallet || mongoose.model('LiveWallet', liveWalletSchema);
